### ISSUE TITLE
Data Flow Diagram: Admin Login

### ISSUE THREAD

**Issue by Spawbreaker** [IntersysConsulting/mdc_team_b_back#3]
- [x] Design
- [x] Approval

**Comment by CrhistianH** [comment]
![E-Commerce - Admin Login](https://user-images.githubusercontent.com/30354352/62809138-b766d380-babf-11e9-9027-b4e657052bda.png)

**Comment by CrhistianH** [comment]
Added "Reset Password" option
![E-Commerce - Admin Login](https://user-images.githubusercontent.com/30354352/63365131-a37f6500-c33c-11e9-9301-d02163846910.png)

**Comment by pablorich** [comment]
I think there's a mistake with some closing tags, also I think it's better if we validate the token and timestamp after the user entered the new password

**Comment by AnaSandoval-Intersys** [comment]
I don't think it's a good idea to validate after user entered new password, after all if the token it's expired it shouldn't let the user interact with the "change password" interface. That validation should come first.

I believe "Reset password" should be an "opt" instead of an "alt", "invalid" should be an "else invalid" instead of "alt invalid" and maybe put the process for Login inside of another "opt", previous to the opt for reset password, just for clarity. 

Otherwise looks great to me.

**Comment by CrhistianH** [comment]
Changes requested by Ana were done.
If you need any other changes to be done (and you will), please discuss them until you all get to an agreement and just let me know the final request.
![E-Commerce Customer Login (2)](https://user-images.githubusercontent.com/30354352/63377631-18ab6400-c356-11e9-9fcc-a535249da4c3.png)

**Comment by CrhistianH** [comment]
Changes requested by Ana are done.
If you need any other changes to be done (and you will), please discuss them until you all get to an agreement and let me know the final request.
![E-Commerce - Admin Login (2)](https://user-images.githubusercontent.com/30354352/63378595-2f52ba80-c358-11e9-82d5-d6cff85fd442.png)
