### ISSUE TITLE
Data Flow Diagram: Customer Login

### ISSUE THREAD

**Issue by Spawbreaker** [IntersysConsulting/mdc_team_b_back#7]
- [x] Design
- [x] Approval

**Comment by CrhistianH** [comment]
![E-Commerce Customer Login](https://user-images.githubusercontent.com/30354352/62808917-1d069000-babf-11e9-8162-5a9ab002a702.png)

**Comment by Spawbreaker** [comment]
Hey Edwin!

I think the  _Verify if Customer's password matches_  is a part of _Compares query result to Customer's input_ and may be integrated, but if there's a reason you kept them separate I'll take your word for it, close the issue and integrate it as is into the project!

**Comment by CrhistianH** [comment]
![E-Commerce Customer Login](https://user-images.githubusercontent.com/30354352/62872903-068d4e00-bce4-11e9-9044-3367f4fdf0bb.png)

**Comment by CrhistianH** [comment]
Added "Reset Password" option 
![E-Commerce Customer Login (1)](https://user-images.githubusercontent.com/30354352/63364913-1e944b80-c33c-11e9-8953-bf0799c5a58e.png)

**Comment by pablorich** [comment]
I think there's a mistake with some closing tags, also I think it's better if we validate the token and timestamp after the user entered the new password

**Comment by AnaSandoval-Intersys** [comment]
Same comment that I made for #3 :
I don't think it's a good idea to validate after user entered new password, after all if the token it's expired it shouldn't let the user interact with the "change password" interface. That validation should come first.

I believe "Reset password" should be an "opt" instead of an "alt", "invalid" should be an "else invalid" instead of "alt invalid" and maybe put the process for Login inside of another "opt", previous to the opt for reset password, just for clarity.

Otherwise looks great to me.

**Comment by CrhistianH** [comment]
Changes requested by Ana were done.
If you need any other changes to be done (and you will), please discuss them until you all get to an agreement and just let me know the final request.
![E-Commerce - Admin Login (1)](https://user-images.githubusercontent.com/30354352/63377654-1cd78180-c356-11e9-93eb-576205108a2e.png)

**Comment by CrhistianH** [comment]
Changes requested by Ana are done.
If you need any other changes to be done (and you will), please discuss them until you all get to an agreement and let me know the final request.
![E-Commerce Customer Login (3)](https://user-images.githubusercontent.com/30354352/63378376-bb181700-c357-11e9-9395-66016765c8ab.png)
